-- ET related codes

INSERT INTO params(grp,name,val) VALUES
	('ET', 'ET', 'ET (in/day)'),
	('ET', 'ETrs', 'ETrs Alfalfa (in/day)'),
	('ET', 'ETos', 'ETos grass (in/day)'),
	('ET', 'MM', 'Mean air temperature (F)'),
	('ET', 'MN', 'Minimum air temperature (F)'),
	('ET', 'MX', 'Maximum air temperature (F)'),
	('ET', 'PE', '24 hour pan evaporation (in)'),
	('ET', 'PP', '24 hour precip (in)'),
	('ET', 'PU', 'Water year precip (in)'),
        ('ET', 'SR', 'ACCUMULATED GLOBAL SOLAR RADIATION (Langleys)'), 
	('ET', 'TA', 'MEAN DAILY RELATIVE HUMIDITY (%)'),
	('ET', 'TG', 'DAILY GROWING DEGREE DAYS  (50 degrees F Base)'),
	('ET', 'UA', 'AVERAGE 24 HOUR WIND SPEED (mph)'), 
	('ET', 'UD', 'RESULTANT 24 HOUR WIND DIRECTION (degrees azimuth)'),
	('ET', 'WG', 'DAILY PEAK WIND GUST (mph)'),
	('ET', 'WR', 'TOTAL WIND RUN (miles/day)'),
	('ET', 'XB', 'MINIMUM DAILY 1" SOIL TEMPERATURE (F)'),
	('ET', 'XC', '   MINIMUM DAILY 4" SOIL TEMPERATURE (F)'),
	('ET', 'XD', 'MINIMUM DAILY 8" SOIL TEMPERATURE (F)'),
	('ET', 'XF', 'MAXIMUM DAILY 1" SOIL TEMPERATURE (F)'),
	('ET', 'XG', 'MAXIMUM DAILY 4" SOIL TEMPERATURE (F)'),
	('ET', 'XH', 'MAXIMUM DAILY 8" SOIL TEMPERATURE (F)'),
	('ET', 'XJ', 'MEAN DAILY 8" SOIL TEMPERATURE (F)'),
	('ET', 'YA', 'MAXIMUM DAILY CANOPY AIR TEMPERATURE (F) (Shielded)'),
	('ET', 'YB', 'MINIMUM DAILY CANOPY AIR TEMPERATURE (F) (Shielded)'),
	('ET', 'YC', 'MAXIMUM DAILY SHELTER AIR TEMPERATURE (F)'),
	('ET', 'YD', 'MINIMUM DAILY SHELTER AIR TEMPERATURE (F)'),
	('ET', 'YL', 'MEAN DAILY 1" SOIL TEMPERATURE (F)'),
	('ET', 'YM', 'MEAN DAILY DEW POINT TEMPERATURE (F)'),
	('ET', 'YW', 'MEAN DAILY 4" SOIL TEMPERATURE (F)'),
	('ET', 'YY', 'MEAN DAILY SHELTER AIR TEMPERATURE (F)'),
	('ET', 'Z1', 'MINIMUM DAILY CANOPY AIR TEMPERATURE (unshielded)'),
	('ET', 'Z2', 'MAXIMUM DAILY CANOPY AIR TEMPERATURE (unshielded)'),
	('ET', 'Z3', 'AVERAGE DAILY CANOPY AIR TEMPERATURE (unshielded)'),  
	('ET', 'ZCM', 'MEAN DAILY 40" SOIL TEMPERATURE (F)'),
	('ET', 'ZCN', 'MINIMUM DAILY 40" SOIL TEMPERATURE (F)'),
	('ET', 'ZCX', 'MAXIMUM DAILY 40" SOIL TEMPERATURE (F)'),
	('ET', 'ZG', 'MINIMUM DAILY 20" SOIL TEMPERATURE (F)'),
	('ET', 'ZH', 'MAXIMUM DAILY 20" SOIL TEMPERATURE (F)'),
	('ET', 'ZK', 'MAXIMUM DAILY  2" SOIL TEMPERATURE (F)'),
	('ET', 'ZL', 'MINIMUM DAILY  2" SOIL TEMPERATURE (F)'),
	('ET', 'ZM', 'MEAN DAILY 2" SOIL TEMPERATURE (F)');
